language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
before_install: cd szerver/
install:
  - pip install requests
script:
  - python3 autoTestClient.py
sudo: enabled
