language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
before_install: pip3 install requests && pip2 install requests && cd szerver/ && sudo chmod +x autoTestClient.py
script:
  - ./autoTestClient.py
sudo: enabled
