# Generated by Django 2.1.4 on 2018-12-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bejegyzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('day', models.IntegerField()),
                ('subj', models.CharField(max_length=120)),
                ('mat', models.CharField(max_length=120)),
                ('pic', models.TextField(max_length=10000)),
            ],
        ),
    ]
