# Generated by Django 2.1.4 on 2018-12-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bejegyzes',
            options={'verbose_name': 'bejegyzés', 'verbose_name_plural': 'bejegyzések'},
        ),
        migrations.AlterField(
            model_name='bejegyzes',
            name='day',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='bejegyzes',
            name='pic',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bejegyzes',
            name='week',
            field=models.IntegerField(default=52),
        ),
    ]
