# Generated by Django 2.1.4 on 2018-12-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181226_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bejegyzes',
            old_name='mat',
            new_name='anyag',
        ),
        migrations.RenameField(
            model_name='bejegyzes',
            old_name='week',
            new_name='het',
        ),
        migrations.RenameField(
            model_name='bejegyzes',
            old_name='day',
            new_name='nap',
        ),
        migrations.RenameField(
            model_name='bejegyzes',
            old_name='subj',
            new_name='tant',
        ),
        migrations.AddField(
            model_name='bejegyzes',
            name='uname',
            field=models.CharField(default='misi', max_length=120),
            preserve_default=False,
        ),
    ]
