# Generated by Django 2.1.4 on 2018-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181226_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bejegyzes',
            name='pic',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
